### ISSUE TITLE
Mqtt commands for Custom Effects?

### ISSUE THREAD

**Issue by LyoshaDovolen** [rorist/sk6812-ws2812fx-mqtt-esp8266#3]
Mqtt commands for basics effects looks like that:
{"color":{"r":83,"g":0,"b":255},"white_value":0,"state":"ON","brightness":255,"effect":"Static","speed":1000}

How looks mqtt commands for "More Then The Basics" and "Custom Effects" may be? 
https://github.com/kitesurfer1404/WS2812FX/blob/master/extras/WS2812FX%20Users%20Guide.md#more-then-the-basics 

Whats meant "Use setSegment() and multiple colors"? Can you show an example command for mqtt?

**Comment by rorist** [comment]
Hi,

setSegment() allow to define an effect to a range of leds instead of them all. Also setColor/setMode actually uses the segments behind the scene anyway.

For now, the effect are taken from WS2812FX like this https://github.com/rorist/sk6812-ws2812fx-mqtt-esp8266/blob/master/ha_mqtt_ledstrip.ino#L68

So implementing custom effect would be a little annoying, but still possible if you want to. I have to work on the thing some time this winter :) Especially to add segments so i can have different statis colors/effect at the same time.
